### ISSUE TITLE
Documentation does not follow Rust's standard documentation format

### ISSUE THREAD

**Issue by sphqxe** [sparkstartconsulting/IBKR-API-Rust#1]
I notice that you have actually left comments documenting each function, but they are not in standard format (see [here](https://doc.rust-lang.org/stable/rust-by-example/meta/doc.html)) and hence they don't show up in the automatically generated documentation when I ran `cargo doc`.

Is this intended? If not I wouldn't mind helping to reformat the comments so that the documentation can be automatically generated.

**Comment by sparkstartconsulting** [comment]
That's been on my todo list, but I got sidetracked with some other things.  If you would like to do that--that would be awesome!!

**Comment by sparkstartconsulting** [comment]
By the way, the comments were copied over mostly from Interactive Broker's python code, but if I recall sometimes from their Java code.  You can refer to that codebase if needed, but I'll be happy to clarify anything as well

**Comment by sparkstartconsulting** [comment]
being worked on in branch [fix_docs_add_tests](https://github.com/sparkstartconsulting/IBKR-API-Rust/tree/fix_docs_add_tests)

**Comment by sparkstartconsulting** [comment]
fixed in [Pull request # 7](https://github.com/sparkstartconsulting/IBKR-API-Rust/pull/7)
