### ISSUE TITLE
print issue in the decode module

### ISSUE THREAD

**Issue by meyergin** [sparkstartconsulting/IBKR-API-Rust#25]
At the /core/decoder.rs, process_error_message uses print function which is frequently line-buffered by default, and the error info would be delayed to display at the io::stdout.
And io::stdout.flush() or switch to println(),
or just remove that as it can be catch at wrapper callback

**Comment by sparkstartconsulting** [comment]
Thanks.  Looks like that was left in from debugging.  I'll remove it next time I check in

**Comment by sparkstartconsulting** [comment]
fixed in d4e89c3
