### ISSUE TITLE
INFO - Connecting INFO - socket either closed or broken, disconnecting Error: IO error: Socket is not connected (os error 57)

### ISSUE THREAD

**Issue by markmark1** [sparkstartconsulting/IBKR-API-Rust#28]
I'm using the Rust wrapper to the IB Gateway API 
(https://github.com/sparkstartconsulting/IBKR-API-Rust).

Everything works dandy if I run the gateway locally, on my machine, and 
connect via IP (127.0.0.1).

However, when I try to connect to any remote gateway host, I get:

INFO - Connecting
INFO - socket either closed or broken, disconnecting
Error: IO error: Socket is not connected (os error 57)

Any ideas what I could be missing?

Cheers,

**Comment by sparkstartconsulting** [comment]
Go into Trader Workstation under Global Configuration.  Go to
API-->Settings.  Uncheck "allow connections from localhost only" and enter
a list of remote machines that you want to whitelist to connect from.

Hope this helps,
Brett

**Comment by virtualritz** [comment]
>  Uncheck "allow connections from localhost only"

@markmark1 posted on my behalf. Sorry for the late reply.
This solved it for me at the time – this can be closed.
